#!/bin/bash

#PS: Mejor no uses gifs porque feh te va a reventar la CPU, ademas de que el gif se mostrara a menos FPS, pero no te voy a parar

fondosdir="$HOME/Fondos/"

if [[ ! -d $fondosdir ]]; then # Si no existe el directorio de fondos se crea y se finaliza ejecucion porque que va a hacer el script si no hay nada
    mkdir $fondosdir
else
    mapfile -t arrayfondos < <( ls $fondosdir | grep -i -e .gif -e .png -e .jpg) # Crea una array con los fondos permitidos
    if [[ ${#arrayfondos[@]} -gt 0 ]]; then # Si la array no esta vacia
        elegido=$(($RANDOM%${#arrayfondos[@]})) # Elige un fondo aleatorio
        archgif=$( grep -i .gif <<< ${arrayfondos[$elegido]} ) # Mira si el elegido es un gif
        if [[ -n $archgif ]]; then # Si es un gif
            # Si el gif es nuevo/su directorio no existe, lo crea, extrae los frames, la duracion de frames (dirgif/frames.txt), y despues entra en bucle de reproduccion
            # Si no es nuevo simplemente lee dirgif/frames.txt, y entra en bucle de reproduccion
            dirgif=$fondosdir${archgif:0:${#archgif}-4}"/" # Quita el .gif, y convierte esta string en el path del directorio de gif
            framesdur=$dirgif"framedur.txt"
            framesfile=$dirgif"frames.txt"
            if [[ ! -d $dirgif ]]; then # Si el dir de gif no existe
                mkdir $dirgif # Se crea el directorio

                ffmpeg -i $fondosdir$archgif $dirgif%d.png # Saca los frames del gif
                ls $dirgif | grep .png >> $framesfile # Coge los frames exportados y los mete a un archivo

                mapfile -t duration < <( ffprobe -show_frames $fondosdir$archgif | grep duration_time= ) 
                # Coge con ffprobe la informacion de los frames del gif, y despues con grep cojo solo "duration_time" y lo paso a una array

                for i in "${duration[@]}"; do
                    echo ${i:14} >> $framesdur # Pasa frame_duration recortado (para que solo sea la duracion y no frame_duration=N) a frames.txt
                done
            fi
            mapfile -t duration < <( cat $framesdur ) # Lee framesdur.txt
            mapfile -t frames < <( cat $framesfile ) # Lee frames.txt
            contador=0
            numframes=${#frames[@]}
            while true; do 
                feh --bg-fill --no-fehbg $dirgif${frames[$contador]}
                sleep ${duration[$contador]}
                contador=$((contador+1))
                if [[ $contador -eq $numframes ]]; then # Si el contador llega al ultimo frame vuelve al primero
                    contador=0
                fi
            done 
            
        else # Si no es un gif (grep devuelve null) simplemente pone el fondo de escritorio
            feh --bg-fill --no-fehbg "$fondosdir${arrayfondos[$elegido]}"
        fi
    fi 
fi